/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthBillingRouteImport } from './routes/_auth/billing'
import { Route as AuthAiRouteImport } from './routes/_auth/ai'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicSuccessRouteImport } from './routes/(public)/success'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as publicBlogIndexRouteImport } from './routes/(public)/blog/index'
import { Route as publicBlogSlugRouteImport } from './routes/(public)/blog/$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillingRoute = AuthBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiRoute = AuthAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/(public)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSuccessRoute = publicSuccessRouteImport.update({
  id: '/(public)/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/(public)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogIndexRoute = publicBlogIndexRouteImport.update({
  id: '/(public)/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogSlugRoute = publicBlogSlugRouteImport.update({
  id: '/(public)/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/about': typeof publicAboutRoute
  '/login': typeof publicLoginRoute
  '/privacy': typeof publicPrivacyRoute
  '/success': typeof publicSuccessRoute
  '/terms': typeof publicTermsRoute
  '/admin': typeof AuthAdminRoute
  '/ai': typeof AuthAiRoute
  '/billing': typeof AuthBillingRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/blog/': typeof publicBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/about': typeof publicAboutRoute
  '/login': typeof publicLoginRoute
  '/privacy': typeof publicPrivacyRoute
  '/success': typeof publicSuccessRoute
  '/terms': typeof publicTermsRoute
  '/admin': typeof AuthAdminRoute
  '/ai': typeof AuthAiRoute
  '/billing': typeof AuthBillingRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/blog': typeof publicBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/(public)/about': typeof publicAboutRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/success': typeof publicSuccessRoute
  '/(public)/terms': typeof publicTermsRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/ai': typeof AuthAiRoute
  '/_auth/billing': typeof AuthBillingRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/blog/$slug': typeof publicBlogSlugRoute
  '/(public)/blog/': typeof publicBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/success'
    | '/terms'
    | '/admin'
    | '/ai'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/success'
    | '/terms'
    | '/admin'
    | '/ai'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/_auth'
    | '/(public)/about'
    | '/(public)/login'
    | '/(public)/privacy'
    | '/(public)/success'
    | '/(public)/terms'
    | '/_auth/admin'
    | '/_auth/ai'
    | '/_auth/billing'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/accept-invitation/$invitationId'
    | '/(public)/'
    | '/(public)/blog/$slug'
    | '/(public)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  publicAboutRoute: typeof publicAboutRoute
  publicLoginRoute: typeof publicLoginRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicSuccessRoute: typeof publicSuccessRoute
  publicTermsRoute: typeof publicTermsRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  publicIndexRoute: typeof publicIndexRoute
  publicBlogSlugRoute: typeof publicBlogSlugRoute
  publicBlogIndexRoute: typeof publicBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/billing': {
      id: '/_auth/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ai': {
      id: '/_auth/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthAiRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/success': {
      id: '/(public)/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof publicSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/': {
      id: '/(public)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof publicBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/$slug': {
      id: '/(public)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof publicBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthAiRoute: typeof AuthAiRoute
  AuthBillingRoute: typeof AuthBillingRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthAiRoute: AuthAiRoute,
  AuthBillingRoute: AuthBillingRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  publicAboutRoute: publicAboutRoute,
  publicLoginRoute: publicLoginRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicSuccessRoute: publicSuccessRoute,
  publicTermsRoute: publicTermsRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  publicIndexRoute: publicIndexRoute,
  publicBlogSlugRoute: publicBlogSlugRoute,
  publicBlogIndexRoute: publicBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
